# Generated by Django 4.2 on 2026-04-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_start_t_1c7039_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_room_id_97310a_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('rejected', 'Отклонено')], default='confirmed', max_length=20, verbose_name='Статус'),
        ),
    ]
