# Generated by Django 4.2 on 2026-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Проектор')),
                ('has_whiteboard', models.BooleanField(default=False, verbose_name='Магнитно-маркерная доска')),
                ('has_video_conf', models.BooleanField(default=False, verbose_name='Видеоконференция')),
                ('has_air_conditioning', models.BooleanField(default=False, verbose_name='Кондиционер')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Переговорная',
                'verbose_name_plural': 'Переговорные',
                'ordering': ['floor', 'name'],
            },
        ),
    ]
